version: '3.9'
services:
  koboldcpp:
    container_name: koboldcpp
    restart: always
    volumes:
      - '${MODEL_DIR}:/models'
    environment:
      - EXTERNAL_IP=${EXTERNAL_IP}
    ports:
      - '192.168.1.18:5001:5001'
    image: '127.0.0.1:5000/koboldcpp-gpu:latest'
    ulimits:
      memlock: -1
    mem_limit: 50gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]
    command:
      [
        "python3",
        "koboldcpp.py",
        "--model",
        "/models/${MODEL}",
        "--host",
        "0.0.0.0",
        "--port",
        "5001",
        "--blasthreads",
        "${BLASTHREADS}",
        "--threads",
        "${THREADS}",
        "--usemlock",
        "--usecublas",
        "--gpulayers",
        "${GPULAYERS}"
      ]
